apiVersion: v1
kind: Service
metadata:
  name: load-balancer-service
spec:
  type: LoadBalancer
  selector:
    app: load-balancer-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
